name: Build P4 Backend
on: push
jobs:
  build-parser-graph:
    runs-on: ubuntu-16.04
    steps:
    - name: Clone source code
      run: |
        sudo git clone --recursive https://github.com/p4lang/p4c.git /p4c
        sudo git clone https://github.com/Yi-Tseng/p4c-ftt.git /p4c-ftt
    - name: Prepare enviroment
      run: |
        sudo chmod +x /p4c/tools/ci-build.sh
        /p4c/tools/ci-build.sh
        sudo mkdir -p /p4c/extensions
        sudo ln -s /p4c-ftt extensions/p4c-ftt
    - name: Build P4 backend
      run: |
        cd /p4c
        sudo ./bootstrap
        cd build && sudo make 
        sudo make install
    - name: Test ftt backend
      run: |
        cd /p4c-ftt/test-data
        sudo make
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: parser-graph
        path: /p4c-ftt/test-data